version: '1.0'
protectables:
    - ANVIL
    - CHIPPED_ANVIL
    - DAMAGED_ANVIL
    - BEACON
    - BREWING_STAND
    - CHEST
    - CAULDRON
    - COMPARATOR
    - REPEATER
    - DISPENSER
    - DROPPER
    - OAK_FENCE_GATE
    - FURNACE
    - HOPPER
    - JUKEBOX
    - NOTE_BLOCK
    - LEVER
    - STONE_BUTTON
    - OAK_TRAPDOOR
    - BIRCH_TRAPDOOR
    - SPRUCE_TRAPDOOR
    - JUNGLE_TRAPDOOR
    - ACACIA_TRAPDOOR
    - DARK_OAK_TRAPDOOR
    - TRAPPED_CHEST
    - OAK_BUTTON
    - BIRCH_BUTTON
    - SPRUCE_BUTTON
    - JUNGLE_BUTTON
    - ACACIA_BUTTON
    - DARK_OAK_BUTTON
    - OAK_DOOR
    - SPRUCE_DOOR
    - BIRCH_DOOR
    - JUNGLE_DOOR
    - ACACIA_DOOR
    - DARK_OAK_DOOR
    - IRON_TRAPDOOR
    - ACACIA_FENCE_GATE
    - BIRCH_FENCE_GATE
    - DARK_OAK_FENCE_GATE
    - JUNGLE_FENCE_GATE
    - SPRUCE_FENCE_GATE
    - ACACIA_PRESSURE_PLATE
    - BIRCH_PRESSURE_PLATE
    - DARK_OAK_PRESSURE_PLATE
    - HEAVY_WEIGHTED_PRESSURE_PLATE
    - JUNGLE_PRESSURE_PLATE
    - LIGHT_WEIGHTED_PRESSURE_PLATE
    - OAK_PRESSURE_PLATE
    - SPRUCE_PRESSURE_PLATE
    - STONE_PRESSURE_PLATE
    - BARREL
    - BELL
    - BLAST_FURNACE
    - CAMPFIRE
    - COMPOSTER
    - DAYLIGHT_DETECTOR
    - LECTERN
    - SMOKER
tool: STICK
chatprefix: SL
populateplayers: true