protectables:
    - ANVIL
    - BEACON
    - BURNING_FURNACE
    - CHEST
    - DIODE_BLOCK_ON
    - DIODE_BLOCK_OFF
    - DISPENSER
    - DROPPER
    - FENCE_GATE
    - FURNACE
    - GOLD_PLATE
    - HOPPER
    - IRON_PLATE
    - JUKEBOX
    - LEVER
    - REDSTONE_COMPARATOR_OFF
    - STONE_BUTTON
    - STONE_PLATE
    - TRAP_DOOR
    - TRAPPED_CHEST
    - WOOD_BUTTON
    - WOOD_PLATE
    - WOODEN_DOOR
    - SPRUCE_DOOR
    - BIRCH_DOOR
    - JUNGLE_DOOR
    - ACACIA_DOOR
    - DARK_OAK_DOOR
    - IRON_TRAPDOOR
    - ACACIA_FENCE_GATE
    - BIRCH_FENCE_GATE
    - DARK_OAK_FENCE_GATE
    - JUNGLE_FENCE_GATE
    - SPRUCE_FENCE_GATE
tool: STICK
chatprefix: SL
autolock: false
populateplayers: true