name: StickyLocks
main: net.simplycrafted.StickyLocks.StickyLocks
author: Brianetta
website: https://github.com/Brianetta/StickyLocks
version: 0.4
commands:
    stickylocks:
        description: Lock objects to prevent other players accessing them
        usage: |
            /<command> show
            /<command> clearselection
            /<command> add <player|group> ...
            /<command> remove <player|group> ...
            /<command> group <group>
            /<command> group <group> {add|remove} <player> ...
            /<command> group <group> {rename|merge} <name>
            /<command> reload
        permission: stickylocks.lock
        aliases: sl
permissions:
    stickylocks.*:
        description: All StickyLocks permissions
        children:
            stickylocks.lock: true
            stickylocks.locksmith: true
            stickylocks.ghost: true
            stickylocks.reload: true
    stickylocks.lock:
        description: Can lock and unlock blocks
        default: yes
    stickylocks.locksmith:
        description: Can manipulate all locks
        default: op
        children:
            stickylocks.lock: true
    stickylocks.ghost:
        description: Locks have no effect
        default: op
    stickylocks.reload:
        description: Can reload the plugin
        default: op
integeration:
    towny: false
