name: StickyLocks
main: net.simplycrafted.StickyLocks.StickyLocks
version: 0.1
commands:
    stickylocks:
        description: Lock objects to prevent other players accessing them
        usage:
        - /<command> show
        - /<command> add [player|group]
        - /<command> remove [player|group]
        - /<command> group [group]
        - /<command> group [group] add [player]
        - /<command> group [group] remove [player]
        - /<command> group [group] rename [name]
        permission: yes
        aliases: sl